package cz.muriel.core.monitoring.bff;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import cz.muriel.core.test.wiremock.WireMockExtension;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

import com.github.tomakehurst.wiremock.WireMockServer;
import com.github.tomakehurst.wiremock.client.WireMock;

/**
 * Security tests for Monitoring BFF
 * 
 * Verifies:
 * - X-Grafana-Org-Id header is always set by backend (never trusted from client)
 * - Service-Access-Token is always regenerated by backend
 * - Forged headers from clients are ignored
 * - Tenant isolation is enforced
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureMockMvc
@ActiveProfiles("test")
@ExtendWith(WireMockExtension.class)
class MonitoringHeaderSecurityIT {

    @Autowired
    private MockMvc mockMvc;

    @Test
    void shouldNotTrustClientProvidedOrgId(WireMockServer wireMock) throws Exception {
        // Setup: Mock Grafana to echo back the Org-Id it received
        wireMock.stubFor(WireMock.post("/api/ds/query")
            .willReturn(WireMock.aResponse()
                .withStatus(200)
                .withHeader("Content-Type", "application/json")
                .withBody("{\"results\":{}}")));

        // Attempt: Client sends forged X-Grafana-Org-Id header
        mockMvc.perform(post("/api/monitoring/ds/query")
                .header("X-Test-Auth", "tenant=TENANT_A;roles=ROLE_USER")
                .header("X-Grafana-Org-Id", "999999")  // FORGED - should be ignored
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"queries\":[{\"refId\":\"A\",\"expr\":\"{app=\\\"test\\\"}\"}]}"))
            .andExpect(status().isOk());

        // Verify: Backend did NOT forward the forged Org-Id
        wireMock.verify(WireMock.postRequestedFor(WireMock.urlEqualTo("/api/ds/query"))
            .withHeader("X-Grafana-Org-Id", WireMock.matching("^(?!999999$).*$")));  // NOT 999999
    }

    @Test
    void shouldNotTrustClientProvidedServiceAccessToken(WireMockServer wireMock) throws Exception {
        wireMock.stubFor(WireMock.post("/api/ds/query")
            .willReturn(WireMock.aResponse()
                .withStatus(200)
                .withHeader("Content-Type", "application/json")
                .withBody("{\"results\":{}}")));

        // Attempt: Client sends forged Service-Access-Token
        mockMvc.perform(post("/api/monitoring/ds/query")
                .header("X-Test-Auth", "tenant=TENANT_A;roles=ROLE_USER")
                .header("Service-Access-Token", "glsa_forged_token_12345")  // FORGED
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"queries\":[{\"refId\":\"A\",\"expr\":\"{app=\\\"test\\\"}\"}]}"))
            .andExpect(status().isOk());

        // Verify: Backend did NOT forward the forged SAT
        wireMock.verify(WireMock.postRequestedFor(WireMock.urlEqualTo("/api/ds/query"))
            .withHeader("Service-Access-Token", WireMock.matching("^(?!glsa_forged_token_12345$).*$")));
    }

    @Test
    void shouldAlwaysSetOrgIdFromTenantMapping(WireMockServer wireMock) throws Exception {
        wireMock.stubFor(WireMock.post("/api/ds/query")
            .willReturn(WireMock.aResponse()
                .withStatus(200)
                .withHeader("Content-Type", "application/json")
                .withBody("{\"results\":{}}")));

        // Request with valid tenant
        mockMvc.perform(post("/api/monitoring/ds/query")
                .header("X-Test-Auth", "tenant=TENANT_A;roles=ROLE_USER")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"queries\":[{\"refId\":\"A\",\"expr\":\"{app=\\\"test\\\"}\"}]}"))
            .andExpect(status().isOk());

        // Verify: Backend set X-Grafana-Org-Id based on TENANT_A mapping
        wireMock.verify(WireMock.postRequestedFor(WireMock.urlEqualTo("/api/ds/query"))
            .withHeader("X-Grafana-Org-Id", WireMock.matching("\\d+")));  // Should be a numeric Org ID
    }

    @Test
    void shouldAlwaysGenerateServiceAccessToken(WireMockServer wireMock) throws Exception {
        wireMock.stubFor(WireMock.post("/api/ds/query")
            .willReturn(WireMock.aResponse()
                .withStatus(200)
                .withHeader("Content-Type", "application/json")
                .withBody("{\"results\":{}}")));

        mockMvc.perform(post("/api/monitoring/ds/query")
                .header("X-Test-Auth", "tenant=TENANT_A;roles=ROLE_USER")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"queries\":[{\"refId\":\"A\",\"expr\":\"{app=\\\"test\\\"}\"}]}"))
            .andExpect(status().isOk());

        // Verify: Backend always sets Service-Access-Token
        wireMock.verify(WireMock.postRequestedFor(WireMock.urlEqualTo("/api/ds/query"))
            .withHeader("Service-Access-Token", WireMock.matching("glsa_.*")));
    }

    @Test
    void shouldIsolateTenantsByOrgId(WireMockServer wireMock) throws Exception {
        wireMock.stubFor(WireMock.post("/api/ds/query")
            .willReturn(WireMock.aResponse()
                .withStatus(200)
                .withHeader("Content-Type", "application/json")
                .withBody("{\"results\":{}}")));

        // Request from TENANT_A
        mockMvc.perform(post("/api/monitoring/ds/query")
                .header("X-Test-Auth", "tenant=TENANT_A;roles=ROLE_USER")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"queries\":[{\"refId\":\"A\",\"expr\":\"{app=\\\"test\\\"}\"}]}"))
            .andExpect(status().isOk());

        String orgIdA = wireMock.getAllServeEvents().get(0)
            .getRequest()
            .getHeader("X-Grafana-Org-Id");

        // Request from TENANT_B
        mockMvc.perform(post("/api/monitoring/ds/query")
                .header("X-Test-Auth", "tenant=TENANT_B;roles=ROLE_USER")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"queries\":[{\"refId\":\"A\",\"expr\":\"{app=\\\"test\\\"}\"}]}"))
            .andExpect(status().isOk());

        String orgIdB = wireMock.getAllServeEvents().get(1)
            .getRequest()
            .getHeader("X-Grafana-Org-Id");

        // Verify: Different tenants get different Org IDs
        assert !orgIdA.equals(orgIdB) : "Tenants must have different Org IDs";
    }

    @Test
    void shouldRejectRequestWithoutTenant() throws Exception {
        // Request without X-Test-Auth (no tenant)
        mockMvc.perform(post("/api/monitoring/ds/query")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"queries\":[{\"refId\":\"A\",\"expr\":\"{app=\\\"test\\\"}\"}]}"))
            .andExpect(status().is4xxClientError());  // 401 or 403
    }

    @Test
    void shouldRejectRequestWithInvalidTenant() throws Exception {
        // Request with non-existent tenant
        mockMvc.perform(post("/api/monitoring/ds/query")
                .header("X-Test-Auth", "tenant=NONEXISTENT;roles=ROLE_USER")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"queries\":[{\"refId\":\"A\",\"expr\":\"{app=\\\"test\\\"}\"}]}"))
            .andExpect(status().is4xxClientError());  // 403 or 404
    }
}
