# 🤖 Minimal Loki configuration for CI/Testing
# This is a simplified version for GitHub Actions and testing

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 50

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# Minimal limits for CI
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  retention_period: 24h
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  per_stream_rate_limit: 256KB
  per_stream_rate_limit_burst: 512KB
  max_concurrent_tail_requests: 10
  max_entries_limit_per_query: 1000

# Minimal storage for CI
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-shipper-active
    cache_location: /loki/tsdb-shipper-cache
    cache_ttl: 1h

# Analytics disabled
analytics:
  reporting_enabled: false